langu.en = {

	DOSIERUNG : "<b>Dosierung</b>",
	DOSIERUNG_INFO : "Verabreichte Dosierung",
	F: "F <i>in %</i>",
	F_INFO: "Bioverfügbarkeit",
	DOSIS: "D <i>in mg</i>",
	DOSIS_INFO: "Dosierung",
	INTERVALL: "<span style=\"font-size:1.5em\">&#964;</span> <i>in h</i>",
	INTERVALL_INFO: "Dosierungsintervall",
	PREDOSE: "C<sub>min</sub> <i>in mg/L</i>",
	PREDOSE_INFO: "Steady-State-Konzentration bei erster Dosierung",
	
	POPULATIONSDATEN : "<b>Populationsdaten</b>",
	POPULATIONSDATEN_INFO : "PK Parameter aus der Fachinfo",
	ABSORPTION: "t<sub>in</sub> <i>in h</i>",
	ABSORPTION_INFO: "Halbwertszeit der Absorbtion nach oraler Gabe",
	HALBWERTSZEIT: "t<sub>1\2</sub> <i>in h</i>",
	HALBWERTSZEIT_INFO: "Halbwertszeit der Konzentration",
	VOLUMEN: "V <i>in L</i>",
	VOLUMEN_INFO: "Verteilungsvolumen",
	CLEARANCE: "Cl <i>in L/h</i>",
	CLEARANCE_INFO: "Berechnete Clearance",
	ELIKONSTANTE: "k<sub>e</sub> <i>in <sup>-h</sup></i>",
	ELIKONSTANTE_INFO: "Berechnete Eliminationskonstante",
	
	PERSONALISIERUNG:"<b>Personalisierung Css</b>",
	PERSONALISIERUNG_INFO:"Berechnung der individuellen PK Parameter",
	KONZENTRATION1: "C<sub>1</sub>",
	KONZENTRATION1_INFO: "Gemessene Konzentration vor der nächsten Dosis (Talspiegel)",
	ZEIT1: "t<sub>1</sub>",
	ZEIT1_INFO: "Zeitpunkt der Messung bezogen auf Therapiebeginn",
	KONZENTRATION2: "C<sub>2</sub>",
	KONZENTRATION2_INFO: "Gemessene Konzentration vor dem Talspiegel (in Eliminationsphase)",
	ZEIT2: "t<sub>2</sub>",
	ZEIT2_INFO: "Zeitpunkt der Messung bezogen auf Therapiebeginn",
	RECHENART: "Keine Berechnung",
	RECHENART_INFO: "Angaben für die Berechnung fehlen",
	RECHENART_VARIATION : "Variation V <b>und</b> t<sub>1/2</sub>",
	RECHENART_VARIATION_INFO : "Variation von entweder Verteilungsvolumen oder Halbwertszeit bei der Berechnung",
	RECHENART_PRECISE : "Personalisiertes V <b>und</b> t<sub>1/2</sub>",
	RECHENART_PRECISE_INFO : "Exakte Berechnung von Verteilungsvolumen und Halbwertszeit",
	
	BEREICH:"<b>Therapeutischer Bereich</b>",
	BEREICH_INFO:"Bereich der Konzentraton aus der Analysenliste",
	OBERE_GRENZE: "Obere Grenze",
	OBERE_GRENZE_INFO: "Obere Grenze entweder Talspiegel oder Spitzenspiegel",
	UNTERE_GRENZE: "Untere Grenze",
	UNTERE_GRENZE_INFO: "Untere Grenze des Talspiegels",
		
	ORDINATE : "C mg/L",
	ABSZISSE : "t in h"
	
};