langu.fr = {

	DOSIERUNG : "<b>dose</b>",
	DOSIERUNG_INFO : "dose administrée",
	F: "F <i>en %</i>",
	F_INFO: "biodisponibilité",
	DOSIS: "D <i>in mg</i>",
	DOSIS_INFO: "dose administrée",
	INTERVALL: "<span style=\"font-size:1.5em\">&#964;</span> <i>in h</i>",
	INTERVALL_INFO: "Intervalle entre les doses",
	PREDOSE: "C<sub>min</sub> <i>en mg/L</i>",
	PREDOSE_INFO: "concentration stable obtenue au premier dosage",
	
	POPULATIONSDATEN : "<b>données démographiques</b>",
	POPULATIONSDATEN_INFO : "paramètres pharmacocinétiques issus de la documentation technique",
	ABSORPTION: "t<sub>in</sub> <i>en heures</i>",
	ABSORPTION_INFO: "temps de demie-vie d'absorption après administration par voie orale",
	HALBWERTSZEIT: "t<sub>1\2</sub> <i>en heures</i>",
	HALBWERTSZEIT_INFO: "temps de demie-vie",
	VOLUMEN: "V <i>in L</i>",
	VOLUMEN_INFO: "volume de distribution",
	CLEARANCE: "Cl <i>en L/h</i>",
	CLEARANCE_INFO: "clairance calculée",
	ELIKONSTANTE: "k<sub>e</sub> <i>in <sup>-h</sup></i>",
	ELIKONSTANTE_INFO: "Berechnete Eliminationskonstante",
	
	PERSONALISIERUNG:"<b>personnalisation</b>",
	//de la concentration à l'équilibre (Css, Concentration steady state)
	PERSONALISIERUNG_INFO:"Calcul des paramètres pharmacocinétiques individuels",
	KONZENTRATION1: "C<sub>1</sub>",
	KONZENTRATION1_INFO: "concentration mesurée avant la dose suivante (résiduelle)",
	ZEIT1: "t<sub>1</sub>",
	ZEIT1_INFO: "point de mesure, par rapport au début du traitement",
	KONZENTRATION2: "C<sub>2</sub>",
	KONZENTRATION2_INFO: "concentration mesurée avant le creux (en phase d'élimination)",
	ZEIT2: "t<sub>2</sub>",
	ZEIT2_INFO: "concentration mesurée avant le creux (en phase d'élimination)",
	RECHENART: "sans calcul",
	RECHENART_INFO: "Certaines données sont manquantes, ne permettant pas le calcul.",
	RECHENART_VARIATION : "variation de V <b>et de</b> t<sub>1/2</sub>",
	RECHENART_VARIATION_INFO : "Variation du volume de distribution ou de la demi-vie, obtenue par calcul",
	RECHENART_PRECISE : "V <b>et</ b> t <sub>1/2</ sub> <b> personnalisés",
	RECHENART_PRECISE_INFO : "calcul rigoureux du volume de distribution et de la demi-vie",
	
	BEREICH:"<b>zone thérapeutique</b>",
	BEREICH_INFO:"plage de concentration issue de la liste d'analyse",
	OBERE_GRENZE: "limite supérieure",
	OBERE_GRENZE_INFO: "limite supérieure des niveaux en pics ou en creux",
	UNTERE_GRENZE: "limite inférieure",
	UNTERE_GRENZE_INFO: "Limite inférieure de la concentration minimale",
		
	ORDINATE : "C mg/L",
	ABSZISSE : "t en h"
	
};
